FROM registry.redhat.io/rhel9-6-els/rhel:9.6@sha256:e7834be17a5c9c22291c6626c0d35e2cc76c062a946c94ac1d2a95fedf7af503 AS builder

RUN INSTALL_PKGS=" \
      gcc-11.5.0 \
      gcc-c++-11.5.0 \
      git \
      llvm-toolset-17.0.6 \
      make \
      openssl-devel \
      rust-toolset-1.75.0 \
      " && \
    dnf install -y $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS

COPY ./logging-vector /opt/app-root/src
WORKDIR /opt/app-root/src

RUN PROTOC=/opt/app-root/src/thirdparty/protoc/protoc-linux-$(arch) make build

RUN cp /opt/app-root/src/target/release/vector /usr/bin

FROM registry.redhat.io/rhel9-6-els/rhel:9.6@sha256:e7834be17a5c9c22291c6626c0d35e2cc76c062a946c94ac1d2a95fedf7af503

COPY --from=builder /usr/bin/vector /usr/bin/

WORKDIR /usr/bin
CMD ["/usr/bin/vector"]

ARG VECTOR_URL
ARG VECTOR_COMMIT
LABEL \
        com.redhat.component="logging-vector-container" \
        cpe="cpe:/a:redhat:logging:6.3::el9" \
        description="Vector container for collection of container logs" \
        distribution-scope="subscription" \
        io.k8s.description="Vector container for collection of container logs" \
        io.k8s.display-name="Vector" \
        io.openshift.build.commit.id=${VECTOR_COMMIT} \
        io.openshift.build.commit.url=${VECTOR_URL}/commit/${VECTOR_COMMIT} \
        io.openshift.build.source-location=${VECTOR_URL} \
        io.openshift.maintainer.product="OpenShift Container Platform" \
        io.openshift.tags="logging,vector,observability" \
        license="Apache-2.0" \
        maintainer="AOS Logging <team-logging@redhat.com>" \
        name="openshift-logging/vector-rhel9" \
        release="6.3" \
        summary="Log collection agent for Red Hat Openshift Logging" \
        url=${VECTOR_URL} \
        vendor="Red Hat, Inc." \
        version_minor="v0.37" \
        version="v0.37.1"
